<?= $this->partial('/common/header.phtml', $this) ?>
資料更新時間: <?= date('c', VoteData::find('time')->data) ?><br>
<?php if ($data = Candidate::findCandidateByVoteId($this->data->id)) { ?>
<pre>
<?= $this->escape(json_encode($data, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT)) ?>
</pre>
候選人 API: <code>http://<?= getenv('API_DOMAIN') ?>/api/candidate/<?= $this->data->id ?></code>
<?php } ?>
<pre>
<?= $this->escape(json_encode(json_decode($this->data->data), JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT)) ?>
</pre>
API: <code>http://<?= getenv('API_DOMAIN') ?>/api/data/<?= $this->data->id ?></code>
<?php if (in_array($this->data->id[0], array('P', 'F'))) { ?>
政黨列表API: <code>http://<?= getenv('API_DOMAIN') ?>/api/party</code>
<?php } ?>
<?= $this->partial('/common/footer.phtml', $this) ?>
