<?= $this->partial('/common/header.phtml', $this) ?>
<h1>請選擇投票類型</h1>
資料更新時間: <?= date('c', VoteData::find('time')->data) ?><br>
<ol>
    <?php foreach (Vote::getVoteTypes() as $id => $name) { ?>
    <li>
    <a href="/index/vote/<?= $id ?>"><?= $id ?> <?= $this->escape($name) ?></a>
    </li>
    <?php } ?>
</ol>
<?php if ($t = VoteData::find('final-time')->data) { ?>
<div class="alert alert-info" role="alert">已於 <?= date('c', $t) ?> 開票完成</div>
<?php } else { ?>
<div class="alert alert-info" role="alert">政黨得票率與當選人分析要等開票完成才有數據可以看</div>
<?php } ?>
<?= $this->partial('/common/footer.phtml', $this) ?>
